APP_NAME: "samplemgr"
APP_PORT: "33001"

# MongoDB URI
#DB_URI: "mongodb://user:password@localhost:27017/dbname?authMechanism=SCRAM-SHA-1"
#DB_NAME: "dbname"

# Postgres
DB_URI: "postgresql://gaurav:4444@localhost:5432/farmeasy?sslmode=disable"
